from .db import Base, SessionLocal, engine
from .models import Category, Item, Settings, User

INITIAL_USERS = [
    "Marcus Vinícius",
    "Marilane",
    "Aline",
    "Lívia",
]

INITIAL_CATEGORIES = [
    {"nome": "Churrasco e Carnes", "cor": "#d63031", "ordem_exibicao": 1},
    {"nome": "Frango e Aves", "cor": "#ffa726", "ordem_exibicao": 2},
    {"nome": "Peixes e Frutos do Mar", "cor": "#29b6f6", "ordem_exibicao": 3},
    {"nome": "Padaria e Massas", "cor": "#d4a574", "ordem_exibicao": 4},
    {"nome": "Laticínios, Ovos e Frios", "cor": "#fbbf24", "ordem_exibicao": 5},
    {"nome": "Hortifruti", "cor": "#66bb6a", "ordem_exibicao": 6},
    {"nome": "Mercearia e Despensa", "cor": "#ff9f43", "ordem_exibicao": 7},
    {"nome": "Bebidas", "cor": "#d946ef", "ordem_exibicao": 8},
    {"nome": "Higiene e Limpeza", "cor": "#2bcbba", "ordem_exibicao": 9},
    {"nome": "Diversos / Casa", "cor": "#a29bfe", "ordem_exibicao": 10},
    {"nome": "Doces e Guloseimas", "cor": "#fd79a8", "ordem_exibicao": 11},
]

INITIAL_ITEMS = {
    "Churrasco e Carnes": [
        "Churrasco Aline 🙋🏻‍♀️",
        "Carvão (trazer extra) 🔥",
        "Álcool churrasco 🔥🔥🔥",
        "Carne Lívia 🥩",
        "Kafta 🍢",
        "Calabresa 🍖🍖🍖",
        "Carne moída 🍖🍖🍖",
        "Carne moída de frango 🍗",
        "Carne para panela 🥘",
        "Carne-seca 🍖🍖🍖",
        "Carne de porco 🐷",
        "Carré 🥩",
        "Costela bovina 🍖",
        "Costela suína 🐷🍖",
        "Cupim churrasco 🍖🍖🍖",
        "Fraldinha 🥩",
        "Linguiça de churrasco 🍢",
        "Linguiça de frango 🍗",
        "Lombo canadense 🥓",
        "Paleta de cordeiro 🍖",
        "Pão de churrasco 🍞🍞",
        "Pão com alho 🧄🧄🧄",
        "Pernil 🍗🍠🍗",
        "Sal de parrilla 🧂🧂🧂",
        "Short ribs 🥩",
        "Torresmo 🥓",
    ],
    "Frango e Aves": [
        "Coração 🐤🐥🐣",
        "Drumet 🍗",
        "Filé de peito de frango 🐥🐥🐣",
        "Frango chimichurri Aurora 🍗🌿",
        "Frango desfiado 🍲",
        "Frango empanado 🐥🐣🐤",
        "Frango fácil Sadia 🍗",
        "Nuggets tradicional 🐥🐣🐤",
        "Nuggets com queijo 🧀",
        "Peito de frango para recheio 🐣🐤🐥",
        "Seara Levíssimo recheado 🐥",
        "Sobrecoxa pronta 🐣🐤🐥",
        "Sobrecoxa ZEROU 🍗❌",
    ],
    "Peixes e Frutos do Mar": [
        "Aliche 🐟🐟🐟",
        "Atum em água e sal 🐟",
        "Bacalhau 🐟🐠🐟",
        "Bolinhos de bacalhau 🐟🐟🐟",
        "Camarão 🍤",
        "Pescada 🐟",
        "Siri 🦀",
        "Tilápia 🐟",
        "Salmão 🍣",
    ],
    "Padaria e Massas": [
        "Bisnaguinha 🥖",
        "Bolo de milho Panquinho 🌽🌽🌽",
        "Bolo de chocolate 🍰",
        "Farinha de trigo 🎂🍰🧁",
        "Macarrão parafuso 🍝🍝🍝",
        "Macarrão fresco 🍝🍝🍝",
        "Macarrão Conchiglione 🐚",
        "Macarrão Fettuccine Paganini 🍝",
        "Macarrão para lasanha 😋😋😋",
        "Macarrão penne 🍝",
        "Macarrão rigatone 🍝",
        "Macarrão ninho 🍝",
        "Macarrão espaguete 🍝",
        "Massa de pastel 🍥🍥🍥",
        "Massa de pizza Supermarket 🍕🍕",
        "Pão francês 🇫🇷 🇫🇷 🇫🇷",
        "Pão de queijo 🧀🧀🧀",
        "Pão de cachorro-quente 🌭🌭🌭",
        "Pão de hambúrguer 🍔🍔",
        "Pão integral Plus Vita 🍞",
        "Pão integral Seven Boys 🍞",
        "Pão Luciano Huck 🥖🥖🥖",
        "Pãozinho 🥐",
        "Pizza 😋😋😋",
        "Pizza de frango 🍕🍗",
        "Rap10 pizza 🍕🍕🍕",
        "Torradas 🍞",
    ],
    "Laticínios, Ovos e Frios": [
        "Leite integral 🐮🐮🐮",
        "Leite semidesnatado 🐮🐮🐮",
        "Leite desnatado 🥛",
        "Leite em pó 🥛",
        "Leite de coco 🥥",
        "Leite de amêndoas 🥛🥜",
        "Leite condensado 🥛🍯",
        "Creme de leite 🍨🍨🍨",
        "Ovos 🍳🍳🍳",
        "Ovos de codorna 🐣🐤🐣",
        "Manteiga 🫓🥖🥐",
        "Qualy 🧈🧈",
        "Muçarela 🍕🧀🍕",
        "Queijo coalho 🧀🧀🧀",
        "Queijo fatiado 🧀🧀🧀",
        "Queijo parmesão 🍕🧀🍕",
        "Queijo para misto 🥪🥪🥪",
        "Queijo ralado 🧀🧀🧀",
        "Queijo Lívia 🧀",
        "Queijo para pastel 🧀",
        "Requeijão 🧀🧀🧀",
        "Catupiry 🧀🧀🧀",
        "Cheddar 🧀",
        "Cream cheese 🥯",
        "Ricota 🧀",
        "Polenguinho 🧀",
        "Provolone 🧀",
        "Peito de peru 🦃",
        "Presunto 🐷🐷🐷",
        "Salame Aurora 🥓🥓🥓",
        "Iogurte Aline 🥛🍓",
        "Iogurte integral natural 🥛",
        "Danoninho 🍓",
        "Pastinha de creme 🥯",
    ],
    "Hortifruti": [
        "Abacaxi 🍍",
        "Melancia 🍉",
        "Laranja 🍊",
        "Uvas 🍇",
        "Acerola 🍒🍒🍒",
        "Cereja 🍒🍒🍒",
        "Azeitona 🫒🫒🫒",
        "Azeitona madura 🫐",
        "Banana 🍌 🍌 🍌",
        "Limão 🍋‍🟩🍋‍🟩🍋",
        "Limão-siciliano 🍋",
        "Uva verde sem caroço 🍇",
        "Uva-passa 🍇🍇🍇",
        "Alho 🧄🧄🧄",
        "Alho-poró 🌿",
        "Alho em pasta 🧄",
        "Cebola 🧅 🧅🧅",
        "Cebola roxa 🧅",
        "Cebola para fritadeira 🧅🍳",
        "Batata 🍟🍟🍟",
        "Brócolis 🥦 🥦🥦",
        "Tomate 🍅🍅🍅",
        "Tomate seco 🍅🍅",
        "Alcaparras 🫛",
        "Aspargos 🥗",
        "Cogumelos 🍄",
        "Palmito 🌴",
        "Cenoura 🥕",
        "Couve-flor 🥦",
        "Espinafre 🍃",
        "Cheiro-verde 🌱🌱🌱",
        "Coentro 🌱🌱🌱",
        "Alecrim 🌿",
        "Louro 🍃",
    ],
    "Mercearia e Despensa": [
        "Arroz 🍙🍘🍙",
        "Feijão-preto 🫛🌱🫛",
        "Feijão-manteiga 🌱🫛🌱",
        "Grão-de-bico 🫛🫘🫛",
        "Ervilha em grão 🍜🍜🍜",
        "Sopa de ervilha 🥣",
        "Azeite de oliva 🫒🫒🫒",
        "Azeite Azul 🫒🔵",
        "Azeite de dendê 🥘",
        "Óleo 🛢️",
        "Vinagre de álcool branco 🍶",
        "Açúcar 🧂",
        "Adoçante ☕",
        "Sal 🧂",
        "Café da Lívia 🔵🔵☕",
        "Café descafeinado azul 💙",
        "Capuccino ☕",
        "Nescafé ☕☕☕",
        "Biscoito maisena 🍪",
        "Biscoito Piraquê de Limão 🍋",
        "Biscoito goiabinha 🍪",
        "Biscoitos cookies 🍪",
        "Biscoitos Bauducco 🍪",
        "Fini 🍬",
        "Batata palha Elma Chips Extrafina 🍟🥔🍟",
        "Milho em lata 🌽",
        "Pipoca de micro-ondas 🍿",
        "Molho de tomate 🍅",
        "Extrato de tomate 🍅",
        "Ketchup 🌭",
        "Mostarda 🌭",
        "Maionese 🐣",
        "Tempero 🧂",
        "Tempero Lemon Pepper 🍋🧂",
        "Páprica defumada 🌶️",
        "Orégano 🌿",
        "Canela 🪵",
    ],
    "Bebidas": [
        "Água com gás 🫗🫗🫗",
        "Água sem gás 💧",
        "Água tônica 🥤",
        "Cerveja 🍺🍺🍺",
        "Cerveja zero 🍺🚫",
        "Coca-Cola Zero 🥃🍸🍷",
        "Pepsi Zero 🍷🍷",
        "Guaraná Aline 🥤",
        "Fanta Uva 🍇",
        "Suco de laranja 🍊",
        "Suco de manga 🥭",
        "Clight limão 🍋‍🟩",
        "Clight abacaxi 🍍",
        "Clight laranja 🍊",
        "Gatorade 🍹",
        "Guaravita 🥤",
        "H2OH! 🍋",
        "Vinho 🍷🍷🍷",
        "Espumante 🥂",
        "Rum 🥃",
        "Vodka 🍸",
        "Skol Beats Aline 🍷🍷🍹",
        "Toddynho 🧃🧃🧃",
        "Xarope Monin Baunilha 🍦",
        "Xarope Monin Laranja 🍊",
    ],
    "Higiene e Limpeza": [
        "Carga de barbear 🪒🪒🪒",
        "Espuma de barbear 🪒",
        "Desodorante Marcus 🧴",
        "Shampoo Pantene 🧴",
        "Shampoo TRESemmé 🧴",
        "Sabonete grande 🧧🧧🧧",
        "Sabonete Francis Red 👽",
        "Pasta de dente grande (não Colgate) 👄👄",
        "Listerine 🧊",
        "Escova de dentes 🪥",
        "Fio dental 🦷",
        "Papel higiênico 🖨️",
        "Papel-toalha 🖨️",
        "Guardanapos 🖨️",
        "Água sanitária 🧼",
        "Cloro 🏊",
        "Pinho Sol 🍾",
        "Detergente neutro 🤢",
        "Sabão em pó 🧺",
        "Sabão líquido Urca azul 🧺",
        "Amaciante Ypê Magia ✨",
        "Esponja abrasiva (não Limppano) 🍴",
        "Esponja azul 🧼",
        "Bombril 🧽",
        "Limppano não risca ✨",
        "Veja Multiuso 👽",
        "Cif Cremoso 🤢",
        "Pano de limpeza 🤢",
        "Pano Perfex 🧼",
        "Pano amarelo de pia 🧽",
        "Saco de pia 🗑️",
        "Saco plástico para congelamento ❄️",
        "Baygon 🦟",
        "SBP 🪳",
        "Veneno para formiga 🐜",
        "Repelente 🧴",
    ],
    "Diversos / Casa": [
        "Papel A4 📄",
        "Papel-alumínio 🖨️",
        "Filme de PVC 🎞️",
        "Pilhas 🔋",
        "Pilhas palito 🔋",
        "Lâmpadas 💡",
        "Tomada 🔌",
        "Isqueiro 🔥🔥",
        "Cera automotiva 🚗",
        "Limpa-piscina 🤽‍♀️🏊‍♂️",
        "Cloro para piscina 🌊",
        "Ração para gato 🐱",
        "Caixa de ferramentas 🧰",
        "Vela de parabéns 🎂",
        "Acetona 💅",
        "Esparadrapo 🩹",
        "Algodão ☁️",
    ],
    "Doces e Guloseimas": [
        "Chocolate 🍫",
        "Barras de chocolate 🍫",
        "Talento 🍫",
        "Bis de Limão 🍋",
        "Belezinha Chocolate 🍫",
        "Pingo de Leite 🍬",
        "Sorvete 🍨🍧🍧",
        "Picolé Sonho de Valsa 🍦",
        "Sorvete Häagen-Dazs 🍨",
        "Geleia de morango 🍓",
        "Geleia diet 🍯",
        "Goiabada em pasta 🍎",
        "Mentos 🍬",
        "Halls cereja 🍒",
        "Paçoca 🥜",
    ],
}


def init_db() -> None:
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        if db.query(User).count() == 0:
            for name in INITIAL_USERS:
                db.add(User(name=name))
            db.commit()

        if db.query(Category).count() == 0:
            for cat in INITIAL_CATEGORIES:
                db.add(Category(**cat))
            db.commit()

        if db.query(Item).count() == 0:
            cat_map = {c.nome: c.id for c in db.query(Category).all()}
            for cat_name, items in INITIAL_ITEMS.items():
                cat_id = cat_map.get(cat_name)
                if not cat_id:
                    continue
                for item_name in items:
                    db.add(
                        Item(
                            nome=item_name,
                            categoria_id=cat_id,
                            ativo=False,
                            quantidade=None,
                        )
                    )
            db.commit()

        if db.query(Settings).count() == 0:
            db.add(
                Settings(id=1, paleta="nocturne", estilo_diferenciacao="elevated")
            )
            db.commit()
    finally:
        db.close()
